fetch email and phone number on authentication
HackerSpace-PESU/pesu-auth pull request #8
Opened 2024-04-16 08:06 UTC by silicoflare

Along with the usual details being fetched, the API now fetches and returns the email address and phone number of the student. This feature will be useful in the apps we plan to build in the future.

2024-04-16 08:07 UTC, silicoflare commented
@aditeyabaral @Icarus131 please lmk if there are any changes, thanks!

2024-04-16 10:08 UTC, aditeyabaral commented
@silicoflare 
Just a comment: Ideally, this API is meant for authentication only, with minimum details returned from it to render placeholders like name, branch, etc. This is just an authentication gateway (to keep things quick), not a way to extract details.

If you are looking to develop apps with the backend APIs where there is a focus on reading details from the website, I would suggest contributing to this: https://github.com/aditeyabaral/pesu-academy-api

2024-04-16 10:11 UTC, aditeyabaral requested changes

2024-04-16 10:11 UTC, aditeyabaral commented on .gitignore
> +
You can remove this extra line

2024-04-16 10:11 UTC, aditeyabaral commented on app/pesu.py
> +        profile["phone"] = soup.find("input", attrs={"id": "updateContact"})["value"]
Handle missing keys:
```python
profile["email"] = soup.find("input", attrs={"id": "updateMail"}).get("value")
```
Same for mobile.

2024-04-16 10:17 UTC, aditeyabaral commented
You also need to update the README with the new data you are returning.

2024-04-16 10:21 UTC, silicoflare commented
> @silicoflare 
> Just a comment: Ideally, this API is meant for authentication only, with minimum details returned from it to render placeholders like name, branch, etc. This is just an authentication gateway (to keep things quick), not a way to extract details.
> 
> If you are looking to develop apps with the backend APIs where there is a focus on reading details from the website, I would suggest contributing to this: https://github.com/aditeyabaral/pesu-academy-api 


So here's the thing: in pesu-tix, when the user signs in using PESU Auth, I want to fetch all these details and store it in a database, so that when the student registers for the event, all those details will be added to the event database record, which cuts the need of the user to fill any additional forms.

2024-04-16 10:22 UTC, silicoflare commented
> You also need to update the README with the new data you are returning.

Yes will do, thanks!

2024-04-16 14:13 UTC, aditeyabaral commented
> > @silicoflare
> > Just a comment: Ideally, this API is meant for authentication only, with minimum details returned from it to render placeholders like name, branch, etc. This is just an authentication gateway (to keep things quick), not a way to extract details.
> > If you are looking to develop apps with the backend APIs where there is a focus on reading details from the website, I would suggest contributing to this: https://github.com/aditeyabaral/pesu-academy-api
> 
> So here's the thing: in pesu-tix, when the user signs in using PESU Auth, I want to fetch all these details and store it in a database, so that when the student registers for the event, all those details will be added to the event database record, which cuts the need of the user to fill any additional forms.

Alright, but no more fields will be added (note to future PR raisers). Please address the requested changes and push a commit.

2024-04-16 16:36 UTC, silicoflare commented
@aditeyabaral i've made the requested changes, please do check!

2024-04-17 06:31 UTC, aditeyabaral approved these changes

2024-04-17 06:31 UTC, merged